global:
  resolve_timeout: 5m
templates:
  - /etc/alertmanager/templates/*.tmpl

route:
  receiver: 'default-receiver'
  group_wait: 30s
  group_interval: 45s
  repeat_interval: 60s
  group_by: [alertname]
  routes:

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname']

receivers:
  - name: 'default-receiver'
    webhook_configs:
      - url: "http://am-alert-printer/alert"
        send_resolved: true
